import { JobListing } from "./types";

export const featuredJobs: JobListing[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp",
    companyInitial: "T",
    location: "Remote",
    type: "Full-time",
    applicantCount: 45,
    salary: { min: 120000, max: 180000, currency: "$" },
    tags: ["React", "Next.js", "TypeScript"],
    postedAt: "2 days ago",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "2",
    title: "UI Developer",
    company: "CyberX",
    companyInitial: "C",
    location: "Remote",
    type: "Contract",
    applicantCount: 12,
    salary: { min: 60000, max: 75000, currency: "$" },
    tags: ["CSS", "Next.js"],
    postedAt: "4h ago",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "3",
    title: "Fullstack Engineer",
    company: "DataFlow",
    companyInitial: "D",
    location: "Munich",
    type: "Hybrid",
    applicantCount: 22,
    salary: { min: 75000, max: 85000, currency: "€" },
    tags: ["Node", "React"],
    postedAt: "1d ago",
    isFeatured: true,
    isNew: true,
  },
];
